# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wordpress
# spec:
#   selector:
#     matchLabels:
#       app: wordpress
#   template:
#     metadata:
#       labels:
#         app: wordpress
#     spec:
#       containers:
#         - name: wordpress
#           image: wordpress:latest
#           env:
#             - name: MYSQL_ROOT_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: mysecret
#                   key: MYSQL_ROOT_PASSWORD
#             - name: MYSQL_DATABASE
#               valueFrom:
#                 secretKeyRef:
#                   name: mysecret
#                   key: MYSQL_DATABASE
#             - name: MYSQL_DATABASE
#               valueFrom:
#                 secretKeyRef:
#                   name: mysecret
#                   key: MYSQL_HOST
#             - name: MYSQL_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: mysecret
#                   key: MYSQL_USER
#             - name: MYSQL_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: mysecret
#                   key: MYSQL_PASSWORD
#           ports:
#             - containerPort: 80
#           resources:

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: wordpress
# spec:
#   type: NodePort
#   selector:
#     app: wordpress
#   ports:
#     - port: 80
#       targetPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wpapp
  name: wpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wpapp
  strategy: {}
  template:
    metadata:
      labels:
        app: wpapp
    spec:
      containers:
        - image: wordpress:latest
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: 10.99.187.110
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecretbox
                  key: u
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecretbox
                  key: p
            - name: WORDPRESS_DB_NAME
              value: lwdb
          resources:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wpapp
  name: wpapp
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wpapp
  type: NodePort
